Ticket4&5
CocoS26/Coco-s-FE-Games pull request #1
Opened 2023-01-10 10:13 UTC by CocoS26

2023-01-10 10:54 UTC, lewispricey requested changes
Good work so far Coco! Really like the semantic HTML tags you're using.

I've left some individual comments of things to change:
- Unrequired validCategories check in the getReviews api call.
- Link to individual article - clicking the category name takes me to an article which could be confusing.
- List for your nav bar doesn't have any list items.

There's a lot of extra code on this ticket that isnt required until way later in the project, please can you make sure to write the minumum code required to satisfy the ticket and remember to use a new branch and pull request for every ticket.

Please raise another PR once the changes have been made :)

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/components/Nav.jsx
> +        return <Link to={`/reviews?category=${category.slug}`} className="Nav__link" key= {category.slug}>{category.slug}
Good work on the Navbar, like the use of slug here for the link and text

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/components/Nav.jsx
> +return <ul>
Realy like the UL here however you arn't using any list items, you may want to wrap your nav links inside LI's

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/components/ReviewCard.jsx
> +        <Link to={`/reviews/${review_id}`}>
Does this all need to be a link, it could be confusing for a user to click the category and reach the individual article.

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/components/ReviewList.jsx
> +    const sortByCategory = searchParams.get('category')
The category filters arn't required until ticket 9

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/components/SingleReview.jsx
> +        <img className="Item_img" src={review_img_url} alt={`picture of ${review_id}`} />
Great use of the review ID in the alt tag

2023-01-10 10:54 UTC, lewispricey commented on northcoders/frontend/games-project/src/utils/api.js
> +    if (validCategories.includes(category)){
Is this required?

2023-01-10 17:05 UTC, Dutton1990 commented
In terms of ticket 4 and 5, I can see all reviews and your links to a single review works fine 👍 
I would however change the link, the link tag is wrapped around a username, it would be better if it was the title. 

In terms of the voting ticket, you aren't optimistically rendering the votes. You want to switch around the order in which you are patching/changing votes on the page. You want to do the patch second. 
You also need to account for error handling, what if the patch request doesn't work? Would be nice to let the user know. 

In terms of the comments ticket, I can't see any comments. I'm not sure if you've just not pushed that component but it's telling me that the comments and addcomments component don't exist. 

Please make these changes and re-send the PR. 

Please try to stick to branching for each ticket, it takes a while to look through so much code 😅 

You also have a curious set up in your folders with some previous sprint work in there? Not sure how that's happened. 

If you want some help with this, please put in an nchelp in the morning and we will try and untangle the confusion together 😄

2023-01-11 11:03 UTC, leekli requested changes
Coco

I'm happy to sign off tickets 6 and 7, they are done. Well done!

For ticket 8, posting a comment, I can see you have a form but it doesn't actually do anything. Looking at the function in commentAdder.jsx it looks like it doesn't do anything as part of the handleSubmit.

Please could you go back to ticket 8 and fix this, I can't currently add or do anything with the comments box.

2023-01-11 11:03 UTC, leekli commented on northcoders/frontend/games-project/src/components/CommentAdder.jsx
> +        // .then
I can't actually add a comment, I suspect that as there's no code here to do the actual api call would be the culprit

2023-01-11 11:27 UTC, merged